### ISSUE TITLE
Hide "Get App" banner

### ISSUE THREAD

**Issue by ponychicken** [rsms/fb-mac-messenger#228] opened 2015-12-05 10:09 UTC
For me there's always this black banner on top of the window, asking me to "get the app".
I actually have it installed on an iPad, but still.

Is there a way to make the wrapper app hide it?

![screenshot 2015-12-05 11 06 15](https://cloud.githubusercontent.com/assets/183302/11607275/8edafb78-9b40-11e5-939a-fbed6378a0c1.png)

**Comment by bradreardon** [comment] 2015-12-07 18:36
Duplicate of #186, putting this here for a reference.

**Comment by rsms** [comment] 2016-02-09 18:05
dupe

**Closed as completed by rsms** 2016-02-09 18:05 UTC
