### ISSUE TITLE
Main window not movable at all in El Capitan

### ISSUE THREAD

**Issue by robco** [rsms/fb-mac-messenger#212] opened 2015-10-14 07:00 UTC
Steps to reproduce:
1. Open FB messenger app
2. Try to move window with mouse
=> Window not movable at all, works fine in Yosemite

**Comment by joshvickerson** [comment] 2015-10-15 15:52
Duplicate of #207.

**Comment by CristianMoisei** [comment] 2015-10-18 16:40
+1 for this.

**Comment by schrackin** [comment] 2015-10-19 13:05
+1

**Comment by framerate** [comment] 2015-10-19 17:26
Use the developer version listed in the readme. @schrackin @CristianMoisei  @joshvickerson @robco

**Comment by ghost** [comment] 2015-10-19 18:33
+1

**Comment by joshvickerson** [comment] 2015-10-21 13:02
@framerate the issue appears to be fixed in the developer version.

**Comment by joevo2** [comment] 2015-10-23 07:28
+1

**Comment by rsms** [comment] 2015-10-27 16:38
dupe

**Closed as completed by rsms** 2015-10-27 16:38 UTC
