### ISSUE TITLE
Retina Element Scaling

### ISSUE THREAD

**Issue by mbillow** [rsms/fb-mac-messenger#218] opened 2015-11-02 18:41 UTC
Certain non-text elements (the new message, information, etc. icons) are not displaying retina assets. This causes the regular DPI images to be upscaled, making them blurry. 

<img width="421" alt="screen shot 2015-11-02 at 13 36 38" src="https://cloud.githubusercontent.com/assets/8651166/10890664/4b272926-8167-11e5-9c69-3e225ef03d46.png">

**Comment by tothandras** [comment] 2015-11-05 10:22
My eyes hurt too.

**Comment by Risengan** [comment] 2015-11-15 14:28
Same problem.

**Comment by joshvickerson** [comment] 2015-11-16 13:56
I think this is a duplicate of #213.

**Comment by mbillow** [comment] 2015-11-16 15:35
Had to reload from server twice before it was fixed, but that was the solution. I believe it is worth looking into how long a cache is kept before the app reloads itself.

**Comment by auermi** [comment] 2015-12-02 20:56
I've reloaded the app multiple times and still am not seeing retina icons.

**Comment by rsms** [comment] 2016-02-09 18:10
This bug is reported over and over — it appears to be a race condition in messenger.com where the code checks for the host window resolution.
No one has been able to reliably reproduce this or describe the circumstances, meaning it's impossible to fix this.
Happy to reopen issue if there's some actual "investigative fruit."

**Closed as completed by rsms** 2016-02-09 18:10 UTC
