### ISSUE TITLE
Unable to drag window once it's focused

### ISSUE THREAD

**Issue by jasonwoodland** [rsms/fb-mac-messenger#188] opened 2015-09-16 03:00 UTC
If you try to drag the app once it's already focused, it'll select the text instead.

Also the drag area is only default 20px high, not the width of the header on messenger.com

El Capitan 10.11 Beta (15A278b)

**Comment by paynerc** [comment] 2015-09-16 15:55
:+1: I have been using this on Yosemite for a while and you can drag the app around. However I just put it on my MBP with El Capitan GM (15A282b) and am experiencing the same issue. I was just coming here to log it and saw this one.

**Comment by dapetcu21** [comment] 2015-09-17 11:15
Same issue, here. Can't drag window on El Capitan.

**Comment by rsms** [comment] 2015-09-17 17:17
How is this different from #156 ?

**Comment by dapetcu21** [comment] 2015-09-17 17:18
Doesn't seem to be. Duplicate.

**Comment by rsms** [comment] 2015-09-17 17:23
Duplicate of #156

**Closed as completed** 2015-09-17 17:22 UTC
