### ISSUE TITLE
New message icon goes behind the os window controls when window is small

### ISSUE THREAD

**Issue by jtenniswood** [rsms/fb-mac-messenger#354] opened 2017-02-02 16:30 UTC
<img width="172" alt="screen shot 2017-02-02 at 4 28 05 pm" src="https://cloud.githubusercontent.com/assets/10881541/22558208/ce7df186-e964-11e6-89d1-43eddaa05dc6.png">

When the window is set to be smaller, the write icon disappears behind the window size/close controls.

**Comment by jacobuid** [comment] 2017-02-13 17:01
#354
I am also experiencing this issue on the Mac, a fix for this would be greatly appreciated


When the window is large it works:
![image](https://cloud.githubusercontent.com/assets/1899414/22893562/a42893e4-f1db-11e6-8049-e7b450028c30.png)



When the window is small, it is broken:
![image](https://cloud.githubusercontent.com/assets/1899414/22893494/74bd13c8-f1db-11e6-9711-71912ff16e9a.png)

**Comment by esimkowitz** [comment] 2017-02-23 16:26
Still an issue in 0.1.12

**Comment by rsms** [comment] 2017-04-06 19:18
It's really hard to fix this, obviously. Either we have to remove the window controls (I can see that generating tons of issue tickets from folks who don't use keyboard shortcuts), or we can remove the compose button, but that will case equally many issue tickets when people can't find "new".

Closing this for now as there's no fix, and it's certainly not a bug.

**Closed as completed by rsms** 2017-04-06 19:18 UTC
