### ISSUE TITLE
Typing is slow and buggy

### ISSUE THREAD

**Issue by szhu** [rsms/fb-mac-messenger#96] opened 2015-04-20 06:20 UTC
I believe this is related to the hack that prevents fixes the system beep. It might also be related to the javascript hacks.

Lately I've having issues typing. When I press some letters in the message box I get no reaction. Sometimes the "Type a message" placeholder remains ghosted over the field even when I have text there. Restarting the or choosing Reload fixes the problem… for a bit.

I don't have any screenshots right now, posting this as soon as possible so that other people who might have this issue can see this. I'll post screenshots when it happens again.

**Comment by joshwertheim** [comment] 2015-04-20 22:57
I've had slow text as well. Sometimes when I type it doesn't seem to register like normal or takes a few seconds to appear.

**Comment by mmontag** [comment] 2015-04-21 23:06
I am having similar experiences. Haven't been able to consistently reproduce or dig deeper yet.

**Comment by rsms** [comment] 2015-06-08 00:35
Unfortunately I can't reproduce.
To debug this, set boolean default key `main.js/disable` to YES and relaunch the app. This disables any modifications to messenger.com — if typing is still slow the issue lies with messenger.com and/or webkit and/or the event logic in FBMApplication. Otherwise the issue is in main.js and we should start investigating there.

**Comment by szhu** [comment] 2015-06-08 00:37
Btw, after I upgraded to Yosemite this issue is largely gone, I think it may be a Mavericks-specific bug.

**Comment by AhemNason** [comment] 2015-06-10 00:44
I had this issue for the first time today after updating to 0.8. Hadn't seen it before today and I've been running the software for about a week.

**Comment by dentarg** [comment] 2015-06-10 10:27
> I had this issue for the first time today after updating to 0.0.8.

Me too, and I'm using Yosemite, so I don't think it's Mavericks specific. I actually have Mavericks on another machine with Messenger 0.0.8, and I haven't seen it there, yet.

**Comment by dentarg** [comment] 2015-06-10 10:33
I tried 

```
defaults write me.rsms.fbmessenger "main.js/disable" -bool YES
```

on my machine with Yosemite. I can't even type any message, I only get the beep sound on keypresses.

**Comment by szhu** [comment] 2015-06-10 10:35
This newest issue is Facebook's fault, I can reproduce it on Safari.

**Comment by gabrielmaldi** [comment] 2015-06-10 13:06
I opened #137 and pretty much think this is the same issue.

**Comment by szhu** [comment] 2015-06-11 17:16
The issue that was Facebook's fault has been resolved I think. `messenger.com` on Safari works fine now.

**Comment by bradreardon** [comment] 2016-02-10 22:31
@rsms wasn't this confirmed to be Facebook's issue and is now fixed?

**Comment by rsms** [comment] 2016-02-11 01:26
Closing this for now. Sounds like it was an issue with messenger.com
If someone can repro in latest release of Messenger.app, please comment and we'll reopen.

**Closed as completed by rsms** 2016-02-11 01:26 UTC
Labels: bug, help wanted
