### ISSUE TITLE
Pasting images doesn't work

### ISSUE THREAD

**Issue by Pr4w** [rsms/fb-mac-messenger#141] opened 2015-06-14 22:48 UTC
Hi,

Stumbled upon this app, looked good so I gave it a try.
So far it all works really nicely aside from one caveat: I can't paste images in chat. Usually I can copy and paste any image (Or ctrl+cmd+shift+4 to screenshot and copy) into the chat, using the official messenger.com, but this doesn't seem to work with the app.

Hope this isn't too much of a hassle to fix !

Cheers,
Mark

**Comment by charleshan** [comment] 2015-06-15 15:34
Duplicate of #109. I am waiting for this fix as well!

**Comment by rsms** [comment] 2016-02-10 18:12
dupe see #109

**Closed as completed by rsms** 2016-02-10 18:12 UTC
Labels: bug, enhancement
