### ISSUE TITLE
After "Reload app from server" header bar disappears

### ISSUE THREAD

**Issue by cowboy** [rsms/fb-mac-messenger#72] opened 2015-04-14 12:50 UTC
Before:

![](http://i.gyazo.com/46402b9564ee5a3bb703445eeb04e535.png)

After:

![](http://i.gyazo.com/fd97c600d759379a1c14242f6c1b6b4b.png)

**Comment by Valpertui** [comment] 2015-04-14 13:21
I do not have this issue on my end, maybe do you have more details about what OS X version you have ?

**Comment by cowboy** [comment] 2015-04-14 13:39
I'm running 10.10.3, I just installed a few days ago so it's relatively stock. Not sure what else I can say that might be helpful!

**Comment by rsms** [comment] 2015-04-15 07:44
Does this happen every time between app launches?
Does it work correctly in Safari (when reloading with regular cmd-r)?

I'm unable to reproduce (on OS X 10.10.3)

**Comment by rsms** [comment] 2015-04-15 07:44
I'll close this for now, until someone else can repro or you've got more details and a theory why this is related to this app and not a messenger.com bug.

**Closed as completed by rsms** 2015-04-15 07:44 UTC
