### ISSUE TITLE
Retina Icons

### ISSUE THREAD

**Issue by jacobp100** [rsms/fb-mac-messenger#45] opened 2015-04-10 17:04 UTC
Menu icons aren’t retina friendly.

**Comment by blakeembrey** [comment] 2015-04-10 18:25
:+1: 

Edit: It randomly switched to retina icons for me just now. I closed it, decided I'd try this again and bam! Retina icons. Sorry it's not more reproducible.

**Comment by jacobp100** [comment] 2015-04-11 18:43
Same happened to me. No idea what happened either.

**Comment by jonathansick** [comment] 2015-04-11 21:05
My experience: on the first launch the icons were low-res, and upon restart the icons are retina. (Using 0.0.4)

Maybe the app can force a re-fresh on new installs to avoid this problem?

**Comment by mattbroussard** [comment] 2015-04-12 18:29
This is due to how Facebook decides whether to serve Retina or non-Retina image assets (you can observe the same behavior on Facebook.com if you reload with the window on a non-Retina secondary display, and then reload with the window on a Retina display).

Jonathan's suggestion to force a refresh on new install seems like a sensible workaround.

**Closed as completed** 2015-04-14 00:43 UTC
