### ISSUE TITLE
Enabling Desktop notifications for the first time doesn't work using the app

### ISSUE THREAD

**Issue by daquinons** [rsms/fb-mac-messenger#23] opened 2015-04-09 10:08 UTC
The window for permissions for Desktop notifications doesn't show up if you are using the app, and it doesn't give any feedback at all. If it's the first time that you enable them you have to go to Safari and enable them there. At least this is what happened to me, if any of you could confirm the issue would be awesome.

Thanks!

**Comment by nirav** [comment] 2015-04-09 21:18
Also the notifications play double sound. One native Mac notification sound + FB notification sound. You can disable the FB one but ideally you should be able to disable the safari one.

**Comment by rsms** [comment] 2015-04-10 00:36
Notifications are a bit messy, mostly because how it's implemented in messenger.com — they rely on some pretty gnarly states, partly stored in localstorage, to "remember" the state (active or not.) You need to manually enable notifications (and disable sounds, if you have enabled OS notification sounds, which I personally haven't.) However, the state of notifications being enabled is currently dodgy in messenger.com and not something this app can do much about.

You're welcome to investigate a fix though ("decompile" messenger.com's JS and dig around)

I'll close this as I can indeed activate notifications in the app, and so **can't reproduce**.

**Closed as completed by rsms** 2015-04-10 00:36 UTC
