### ISSUE TITLE
I cant get notifications for new messages

### ISSUE THREAD

**Issue by AchoArnold** [rsms/fb-mac-messenger#150] opened 2015-06-28 05:11 UTC
When someone sends me a message, I don't seem to get any notifications. I get the sound but I don't get the notification panel which appears on the top right of the screeen

**Comment by cwramsey** [comment] 2015-06-29 19:49
Same over here. I get the sound (which is usually masked by music playing) but no notification ever shows up. In the previous version these worked fine, but after the most recent update they stopped working.

**Comment by coderanger** [comment] 2015-07-12 05:46
Possibly related to https://github.com/rsms/fb-mac-messenger/issues/133? Check if it works if the app is explicitly in the background.

**Comment by rsms** [comment] 2015-08-13 02:53
@coderanger Nice catch.
Duplicate of #133

**Closed as completed by rsms** 2015-08-13 02:53 UTC

**Comment by unitbroker** [comment] 2015-08-14 18:52
New job with southern Cali apparel manufacturer
Here's a 5$ coupon. http://shop.pe/iD1nT
If I sell $500 dollars by 5pm x-apple-data-detectors://2 I keep my lights
on!
We have really cool stuff!
Have a good weekend!

On Saturday, July 11, 2015, Noah Kantrowitz notifications@github.com
wrote:

> Possibly related to #133
> https://github.com/rsms/fb-mac-messenger/issues/133? Check if it works
> if the app is explicitly in the background.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rsms/fb-mac-messenger/issues/150#issuecomment-120689952
> .

## 

Rob Estes
Ipad_1
Unitbroker@gmail.com
602-319-4052
