### ISSUE TITLE
Clicking on photo disables app

### ISSUE THREAD

**Issue by Gunny123** [rsms/fb-mac-messenger#180] opened 2015-08-25 00:24 UTC
When a user uploads a new photo and you go to click on the photo to enlarge. You cannot cannot exit the window that displays. You are forced to quit and relaunch the app. 

System specs: 
Mac OS X 10.10.5
Mid 2013 13" Macbook Air
FB Messenger for Mac version: 0.1.3 (latest release)

**Comment by rsms** [comment] 2016-02-09 18:26
Can't reproduce.
(I assume you know that you click outside the photo to close it, or press the esc key)

**Closed as completed by rsms** 2016-02-09 18:26 UTC
