### ISSUE TITLE
El Capitan beta 3 issues

### ISSUE THREAD

**Issue by homoky** [rsms/fb-mac-messenger#157] opened 2015-07-12 10:51 UTC
1) window is not draggable

2) when i launch app it works great, but when it reloads, this happens to left sidebar: 

![screenshot 2015-07-12 v 12 50 49](https://cloud.githubusercontent.com/assets/893917/8637515/c3502c80-2894-11e5-86ec-efeca09d1c7b.png)

**Comment by spyesx** [comment] 2015-07-12 16:41
Same for me but it looks like a build from the new xcode could fix it. I'm not an iOS dev but my OS keeps asking for a new version of xcode that I can't download yet.

**Comment by loonghuey** [comment] 2015-07-15 02:56
The problem seems to persist when you open messenger.com with Safari, so I guess it's nothing @rsms can fix?

**Comment by homoky** [comment] 2015-07-15 18:50
Yes, you are right. In Safari helps when I change broswer agent to Chrome for example.

**Comment by rsms** [comment] 2015-08-13 02:31
Is this still an issue? The Messenger.com team continually makes improvements.

**Comment by irae** [comment] 2015-08-20 21:06
Not dragging is still an issue in El Captain beta 5. The reload issue don't exist anymore.
I think the issue can be renamed to "Impossible to drag window in El Captain Beta".

**Comment by rsms** [comment] 2015-09-17 17:17
Duplicate of #156

**Closed as completed by rsms** 2015-09-17 17:17 UTC
