### ISSUE TITLE
Unable to add emojis using the osx emojipopup

### ISSUE THREAD

**Issue by ssssamstrup** [rsms/fb-mac-messenger#287] opened 2016-04-12 10:32 UTC
Pressing CTRL+CMD+SPACE brings up a popup where emojis can be added. When trying to do this in the app, the popup appears but when an emoji is chosen, it isn't written to the text-field (in some cases the emoji appears in the text-field for a moment, but then disappears again the next).

Screen-recording of issue: https://dl.dropboxusercontent.com/u/478737/Messengerformac-emojipop.mov

**Comment by joshvickerson** [comment] 2016-04-12 21:40
Duplicate of #238.

**Comment by mariusfanu** [comment] 2016-05-09 06:22
I have the same issue.

**Comment by blazeworx** [comment] 2016-05-12 15:39
+1 Also happening for me.

**Comment by Allariah** [comment] 2016-11-15 20:16
Still occurring as of 
Sierra: 10.12.1, Messenger 0.1.10

**Comment by rsms** [comment] 2016-11-21 17:10
dupe of #238

**Closed as completed by rsms** 2016-11-21 17:10 UTC
