### ISSUE TITLE
App triggers high perf graphics card on 2016 15" Macbook Pros

### ISSUE THREAD

**Issue by html5cat** [rsms/fb-mac-messenger#346] opened 2016-12-27 00:53 UTC

**Comment by computergeek125** [comment] 2016-12-28 23:57
I can confirm the bug.

I have a 15" mid-2014 Macbook Pro Retina (2.8GHz i7-4980HQ, 16GB RAM, Iris Pro 5200 + Nvidia GeForce GT 750m) running OS X 10.12.3 Beta (16D17a) (Darwin 16.4.0)

According to Activity Monitor and gfxCardStatus, this app places my computer in high-performance graphics mode, forcing the GT 750m to turn on.  It's not an issue when my laptop is plugged in, but it would be nice to be able to take advantage of the more energy-efficient Iris Pro while leaving this app in the background.  Would it be possible for this app to be able to be run on the Iris Pro instead of the GT?  

I know there is a bug in iMessage which causes the high-performance graphics to be turned on and get stuck that showed up in one of the past few macOS builds, but I don't think this is related to that since it occurs at app launch.  Relaunching iMessage resolved the issue.  Neither relaunching FB Messenger nor restarting the computer resolve this.

**Comment by felixbinder** [comment] 2017-01-12 14:37
I can also confirm this on a Mid 2014 rMBP. 
<img width="281" alt="screen shot 2017-01-12 at 15 36 19" src="https://cloud.githubusercontent.com/assets/24477285/21893835/12abf8be-d8dd-11e6-9f30-5c400da2414a.png">

**Comment by greg** [comment] 2017-01-14 06:16
PR #344 fixes this issue (maintainer doesn't seem to be present to merge PRs, but you can clone and build yourself)

**Comment by rsms** [comment] 2017-01-17 03:27
Fixed by #344 authored by @greg

**Comment by qwebar** [comment] 2017-01-23 06:53
Could someone explain how can i get the issue fixed? I just switched to mac and dont understand/know how to clone and build this into an .dmg file that i can install. 
Thanks in advance!

**Comment by computergeek125** [comment] 2017-01-25 02:14
You have to build it yourself since there's no prebuilt release yet.  Clone it somewhere on your computer, `cd` to the cloned repo, then run `xcodebuild` and copy `./build/Release/Messenger.app` to wherever you want it.

Building against master worked for me to fix this issue.

**Comment by greg** [comment] 2017-01-25 03:09
re previous comment, note that you'll need to install Xcode in order to do this. If you don't like command line, you can also open the xcodeproj file in Xcode and build from there (then you can find the app under the Products folder in the left pane -- right click > show in Finder)

I think this issue can be closed now (since it's resolved)?

**Comment by computergeek125** [comment] 2017-01-25 04:42
Sorry about that.  I'm used to Linux and BSD where everything is `make`, `make install`.  

I'd agree that it can be closed.

**Comment by vassilmladenov** [comment] 2017-01-29 19:27
Can confirm that recompiling does fix the discrete graphics switching. However, I believe a new minor release should be pushed in order to close this issue, since the main download page and Homebrew Cask both point to 0.1.10

**Comment by ITJamie** [comment] 2017-02-02 19:47
Same issue on 2016" macbooks (touchbar) with discrete graphics

**Comment by rsms** [comment] 2017-02-11 21:59
Version 0.1.11 just published which contains [the fix](https://github.com/rsms/fb-mac-messenger/commit/420db4a3b3b64255fc429349506a579ab5fad8ca) for this issue.

**Closed as completed by rsms** 2017-02-11 21:59 UTC
