### ISSUE TITLE
All messenger is blank (white)

### ISSUE THREAD

**Issue by romanbitca** [rsms/fb-mac-messenger#377] opened 2017-04-03 08:09 UTC
After restarting my Mac, notice that Messenger is blank. CMD+R, SingOut, Reinstalling, do not help.

![Screenshot here](http://image.prntscr.com/image/3ea4fb04558640948b0fe953caf9c0d0.png)

**Comment by johankman** [comment] 2017-04-03 11:07
Got the exact same problem..

**Comment by pavelbedi** [comment] 2017-04-03 15:28
Me too ☹️

**Comment by felixSpark** [comment] 2017-04-03 23:18
Logs are as follows

```
4/04/17 11:16:41.497 am SIMBL Agent[24296]: warning: failed to get scripting definition from /Applications/Messenger.app; it may not be scriptable.
4/04/17 11:16:41.507 am SIMBL Agent[24299]: warning: failed to get scripting definition from /Applications/Messenger.app; it may not be scriptable.
4/04/17 11:16:41.678 am Messenger[24635]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
```

**Comment by TGNYC** [comment] 2017-04-03 23:53
Same.

**Comment by rsms** [comment] 2017-04-03 23:58
Strange. I can't reproduce (macOS 10.12.3 16D32)

Those log messages are for macOS scripting, which the app doesn't provide (mac apps do provide some default scripting, which is probably what the log messages are about.)

To reset all local state for the app, first quit the app and then, in a terminal:

```txt
defaults delete me.rsms.fbmessenger
rm -rf ~/Library/Caches/me.rsms.fbmessenger ~/Library/Caches/me.rsms.fbmessenger
```

Finally, you can optionally delete cookies for facebook.com and messenger.com in Safari, and optionally clear any related entries in Keychain.

Relaunching the app should put you in a clean-slate state.

**Comment by rsms** [comment] 2017-04-04 00:02
Also, can you please provide:

- OS versions (find it under "Software" in "System information")
- Machine info (find it under "Hardware" in "System information", and please leave out your serial numbers!)

And finally, since this might be related to a recent GPU optimization:

- GPU/display info (find it under "Graphics/Displays" in "System Information")

----

Here's my info:

```
Software
  System Version:	macOS 10.12.3 (16D32)
  Kernel Version:	Darwin 16.4.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

Hardware
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,5
  Processor Name:	Intel Core i7
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP114.0172.B13
  SMC Version (system):	2.30f2

Graphics/Display:
AMD Radeon R9 M370X:
  Chipset Model:	AMD Radeon R9 M370X
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2048 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x6821
  Revision ID:	0x0083
  ROM Revision:	113-C5670E-777
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.20 [3.2.8]
  EFI Driver Version:	01.00.777
  Metal:	Supported
  Displays:
Color LCD:
  Display Type:	Retina LCD
  Resolution:	2880 x 1800 Retina
  Retina:	Yes
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	No
  Built-In:	Yes
```

**Comment by felixSpark** [comment] 2017-04-04 00:08
Deleted defaults and cache. Deleted Safari cookie. No Keychain entry. When I relaunch the app it asks me to log in and do 2 factor authentication. Then it goes to blank screen again.

System Software Overview:

  System Version:	OS X 10.10.4 (14E46)
  Kernel Version:	Darwin 14.4.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,2
  Processor Name:	Intel Core i5
  Processor Speed:	1.4 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	4 GB
  Boot ROM Version:	MBA61.0099.B19
  SMC Version (system):	2.13f15

Intel HD Graphics 5000:

  Chipset Model:	Intel HD Graphics 5000
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x0a26
  Revision ID:	0x0009
  Displays:
Color LCD:
  Display Type:	LCD
  Resolution:	1440 x 900
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Built-In:	Yes

**Comment by ibruno** [comment] 2017-04-04 00:09
Same as felix.

Follow my info:

```
Software:
  Versão do Sistema:	macOS 10.12.4 (16E195)
  Versão de Kernel:	Darwin 16.5.0
  Volume de Inicialização:	Macintosh HD
  Modo de Inicialização:	Normal

Hardware:

  Nome do Modelo:	MacBook Pro
  Identificador do Modelo:	MacBookPro11,4
  Nome do Processador:	Intel Core i7
  Velocidade do Processador:	2,2 GHz
  Número de Processadores:	1
  Número Total de Núcleos:	4
  Cache L2 (por Núcleo):	256 KB
  Cache de L3:	6 MB
  Memória:	16 GB
  Versão da ROM de Inicialização:	MBP114.0172.B16
  Versão do SMC (sistema):	2.29f24

Graphics/Display:
Intel Iris Pro:
  Modelo do Chipset:	Intel Iris Pro
  Tipo:	GPU
  Barramento:	Integrado
  VRAM (Dinâmica, Máx.):	1536 MB
  Fornecedor:	Intel (0x8086)
  ID do Dispositivo:	0x0d26
  ID da Revisão:	0x0008
  Metal:	Compatível
  Monitores:
LCD Colorido:
  Tipo do Monitor:	LCD Retina Integrado
  Resolução:	2880 x 1800 Retina
  Profundidade em Pixels:	Cor de 32 Bits (ARGB8888)
  Monitor Principal:	Sim
  Espelho:	Desligado
  On-line:	Sim
  Rotação:	Compatível
  Ajustar Brilho Automaticamente:	Sim
  Tipo de Conexão:	DisplayPort

```

**Comment by rsms** [comment] 2017-04-04 00:23
Oh, it might be 2-factor auth. It's a long time ago since I worked at Facebook and things might have changed a lot — maybe 2FA relied on some security feature in web browsers that this app (being sort of a simple web browser) doesn't provide.

I used 2FA myself, so I'll try actually signing out.

**Comment by ibruno** [comment] 2017-04-04 00:25
Sorry, I forget to mention. I'm not using 2FA on Facebook.

**Comment by TGNYC** [comment] 2017-04-04 01:12
```
System Software Overview:

  System Version:	macOS 10.12.2 (16C67)
  Kernel Version:	Darwin 16.3.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

Hardware Overview:

  Model Name:	iMac
  Model Identifier:	iMac12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	12 GB
  Boot ROM Version:	IM121.0047.B25
  SMC Version (system):	1.71f22

AMD Radeon HD 6770M:

  Chipset Model:	AMD Radeon HD 6770M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Total):	512 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x6740
  Revision ID:	0x0000
  ROM Revision:	113-C0170C-170
  EFI Driver Version:	01.00.544
  Displays:
iMac:
  Display Type:	LCD
  Resolution:	1920 x 1080
  Pixel Depth:	32-Bit Color (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Built-In:	Yes
```

No 2FA for me.

Please let me know if I added information that is private/should not be given, and I will delete this comment immediately.

**Comment by felixSpark** [comment] 2017-04-04 03:00
Despite the window being blank, there is still a badge appearing on the dock icon when a message is received, showing that it is still receiving messages from FB.

________________________________

**Comment by rsms** [comment] 2017-04-04 05:25
When the window is blank, is it actually completely empty, or are there window control buttons, and  is there a progress bar? I'm assuming by "blank" you mean completely empty, but just want to be sure.

**Comment by johankman** [comment] 2017-04-04 06:01
This is what it looks like on my computer. Tried deleting prefs.
I dont use 2FA. 

When i start the Application i see a status bar that moves. Then it goes all white. 

![screen shot 2017-04-04 at 08 00 03](https://cloud.githubusercontent.com/assets/26870578/24643214/d8c65cb4-190c-11e7-84bf-e2224e2590b4.png)

**Comment by johankman** [comment] 2017-04-04 06:03
System Software Overview:

  System Version:	macOS 10.12.4 (16E195)
  Kernel Version:	Darwin 16.5.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	26 minutes

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,2
  Processor Name:	Intel Core i5
  Processor Speed:	2,9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
  Boot ROM Version:	MBP132.0226.B15
  SMC Version (system):	2.37f20

Intel Iris Graphics 550:

  Chipset Model:	Intel Iris Graphics 550
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel (0x8086)
  Device ID:	0x1927
  Revision ID:	0x000a
  Metal:	Supported
  Displays:
DELL U2715H:
  Resolution:	2560 x 1440 @ 60 Hz
  Pixel Depth:	30-Bit Color (ARGB2101010)
  Display Serial Number:	GH85D68P03XS
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort

**Comment by pavelbedi** [comment] 2017-04-04 06:09
After reinstall app, cache, I am still logged in Messenger. This may be the cause of the problem.
(notifications works)

**Comment by ibruno** [comment] 2017-04-04 09:19
App dont ask me to do login on my fb account (even after reinstall the app).

And the progress bar appears (when open the app and when reload).

![captura de tela 2017-04-04 as 06 16 47](https://cloud.githubusercontent.com/assets/3800745/24649699/5c5aba66-18fe-11e7-9a6e-33fbfed765a9.png)

**Comment by pavelbedi** [comment] 2017-04-04 10:18
**It works now!**

**Comment by johankman** [comment] 2017-04-04 10:47
So what did you do? :)
Mine is still the same.

**Comment by ibruno** [comment] 2017-04-04 11:48
@pavelbedi ?

**Comment by pavelbedi** [comment] 2017-04-04 12:07
I just randomly open app 😮

**Comment by genesiscz** [comment] 2017-04-04 12:29
Same problem

**Comment by przemyslawhaptas** [comment] 2017-04-04 12:36
Same here.

**Comment by zenopopovici** [comment] 2017-04-04 13:19
Same issue :(

**Comment by AkitakiLab** [comment] 2017-04-04 13:26
Same issue here on MacBook Pro 2015, macOS 10.12.3.
I've tried reinstalling the app, clearing the caches but still not working.
The window is completely blank as shown in pictures by johankman.

**Comment by alexleetw87** [comment] 2017-04-04 14:57
Same issue here :(

**Comment by kacboy** [comment] 2017-04-04 16:36
Did the terminal command and cleared my Safari cache and reinstalled the app with no success. :(

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	16 GB

**Comment by joenot443** [comment] 2017-04-04 22:32
Adding my +1 here - I've had this problem before and it was fixed by restarting my Mac or logging out, this time no dice though.

**Comment by raxod502** [comment] 2017-04-04 22:53
I got this problem on installing the app fresh (never tried it before). If there haven't been any commits for a few weeks, I would assume this is an update on Facebook's end?

Interestingly, when I downloaded the latest release, it presented me immediately with the loading bar and then a white screen. But when I installed from

    $ brew cask install messenger

I was prompted for my username and password. Only after entering those was I given the same blank screen.

**Comment by LaancX** [comment] 2017-04-04 23:07
It may be a problem related to the connection between the app and the messenger server from facebook. I'm not an expert, it's just a hypothesis. 

With the information that raxod give us about the white screen just about installing the app, it can be the protocol of security from facebook blocking the 3rd app.

**Comment by thenexus00** [comment] 2017-04-05 00:50
I actually do not think it is a connection issue. It seems to receive notifications and feels like it has connected. 
When you load the app it has a fadeIn effect on the UI and it seems what ever error it is prevent the UI from loading in after the load bar.

Also happening for me as well as everyone else. 
Thing is I updated an it worked fine and then I shut down yesterday and booted it up and its white. My macbook pro is rocking the same version but I have not closed the app and it is still working.

**Comment by thenexus00** [comment] 2017-04-05 02:04
The app goofy which is a very similar app is running and working.

**Comment by LaancX** [comment] 2017-04-05 02:53
indeed it is very similar. I guess I'll stick with the goofy for a while. Thanks for the advice thenexus00, :)

**Comment by karteek-paruchuri** [comment] 2017-04-05 05:24
I just started facing the same problem. Had to switch to Goofy

**Comment by panr** [comment] 2017-04-05 08:22
@rsms I have this bug after installing latest MacOS update... Is it related?

**Comment by vamidi** [comment] 2017-04-05 08:32
Yesterday I had no white screen now this morning I have one. tried reinstalling, delete cookies & restarting it. nothing seems to work. I am on MacOS

  Modelnaam:	MacBook Pro mid 2014
  Modelaanduiding:	MacBookPro11,3
  Processornaam:	Intel Core i7
  Processorsnelheid:	2,5 GHz
  Aantal processors:	1
  Totale aantal cores:	4
  L2-cache (per core):	256 KB
  L3-cache:	6 MB
  Geheugen:	16 GB

**Comment by nick-barth** [comment] 2017-04-05 11:00
Broken for me as well.

macOS: Sierra 10.12.1
MacBook Pro (Retina, Mid 2012)

**Comment by ghost** [comment] 2017-04-05 11:12
same here white screen still got notification but white screen

> 

> System Software Overview:
> 
>   System Version:	macOS 10.12.4 (16E195)
>   Kernel Version:	Darwin 16.5.0
>   Boot Volume:	Macintosh HD
>   Boot Mode:	Normal
>   Secure Virtual Memory:	Enabled
>   System Integrity Protection:	Enabled
>  
> Intel HD Graphics 5000:
> 
>   Chipset Model:	Intel HD Graphics 5000
>   Type:	GPU
>   Bus:	Built-In
>   VRAM (Dynamic, Max):	1536 MB
>   Vendor:	Intel (0x8086)
>   Device ID:	0x0a26
>   Revision ID:	0x0009
>   Metal:	Supported
>   Displays:
> DELL UP2716D:
>   Resolution:	2560 x 1440 @ 59 Hz
>   Pixel Depth:	32-Bit Color (ARGB8888)
>   Main Display:	Yes
>   Mirror:	Off
>   Online:	Yes
>   Rotation:	Supported
>   Automatically Adjust Brightness:	No
>   Connection Type:	DisplayPort
> 
> Hardware Overview:
> 
>   Model Name:	Mac mini
>   Model Identifier:	Macmini7,1
>   Processor Name:	Intel Core i5
>   Processor Speed:	1.4 GHz
>   Number of Processors:	1
>   Total Number of Cores:	2
>   L2 Cache (per Core):	256 KB
>   L3 Cache:	3 MB
>   Memory:	4 GB
>  
> 
>

**Comment by manbeardave** [comment] 2017-04-05 13:42
Adding my +1.  Deleting cache and cookies didn't work.  I've tried yelling at it, I've tried hitting it, I'm all out of ideas.

**Comment by igorkulman** [comment] 2017-04-05 13:50
Same  here, macOS 10.12.4

**Comment by oskarlin** [comment] 2017-04-05 15:26
+1 here

**Comment by awwang** [comment] 2017-04-05 15:35
Problem started yesterday. White screen on macOS 10.12.3, Macbook Pro (Retina, 15-inch, Late 2013). Reloading, reinstalling, or clearing caches/cookies do not work. Nothing has been changed in my Facebook account settings.

**Comment by oskarlin** [comment] 2017-04-05 15:50
The messages show up in notification center still though.

**Comment by waveman777** [comment] 2017-04-05 16:43
Got the exact same problem.

**Comment by russelltrafford** [comment] 2017-04-05 16:51
Still an issue. Started yesterday I think. Or day before? I'll provide some screenshots, although, its... well blank 😂 
<img width="501" alt="screen shot 2017-04-05 at 9 49 20 am" src="https://cloud.githubusercontent.com/assets/22302818/24716916/68b53f56-19e5-11e7-96cd-46d560a410a6.png">
![screen shot 2017-04-05 at 9 52 19 am](https://cloud.githubusercontent.com/assets/22302818/24716956/9e28adb2-19e5-11e7-97ec-f6a35dbd7135.png)

**Comment by nghtstr** [comment] 2017-04-05 17:11
This started for me today. I was actually using it when it said it needed a refresh. I did that and it has been a blank screen ever since.

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB
  Boot ROM Version:	MBP133.0226.B15
  SMC Version (system):	2.38f7

<img width="242" alt="screen shot 2017-04-05 at 10 11 02 am" src="https://cloud.githubusercontent.com/assets/51501/24717690/33fa8642-19e8-11e7-843f-0329310613c7.png">

**Comment by thepatres** [comment] 2017-04-05 17:24
Same here. Exactly like @nghtstr 

Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir4,2
  Processor Name:	Intel Core i5
  Processor Speed:	1,7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	4 GB
  Boot ROM Version:	MBA41.0077.B1B
  SMC Version (system):	1.73f66

**Comment by cvx** [comment] 2017-04-05 17:26
Here's the root of the problem, no need for more reports 😉:
`ReactMount` module is no longer available in the app by simply doing `require('ReactMount')`. It probably was a incremental rollout, which could be the reason why @rsms couldn't reproduce the issue earlier. I think it's still possible to get that module by defining `__REACT_DEVOOLS_GLOBAL_HOOK__.inject` function before Messenger code is executed.

Here's a snippet of Messenger code:
```javascript
"undefined" != typeof __REACT_DEVTOOLS_GLOBAL_HOOK__ && "function" == typeof __REACT_DEVTOOLS_GLOBAL_HOOK__.inject && __REACT_DEVTOOLS_GLOBAL_HOOK__.inject({
    ComponentTree: (…),
    Mount: uv,
    Reconciler: po
});
```

**Comment by pavelbedi** [comment] 2017-04-05 17:28
Again 😢

**Comment by manbeardave** [comment] 2017-04-05 17:30
@CvX good stuff man, thanks for posting your findings!

**Comment by russelltrafford** [comment] 2017-04-05 18:19
@CvX nice one! Open source community work for the win! 😃

**Comment by rsms** [comment] 2017-04-05 18:31
Good catch @CvX! We should make sure that in the future, the app doesn't "crash" when the main js file faults.

Okay, so it's happening for me now too, which is good. However, `__REACT_DEVTOOLS_GLOBAL_HOOK__` is not defined on the global object. I wonder if there's something else going on.

**Comment by nghtstr** [comment] 2017-04-05 19:11
Do we have an idea when a fix is going to be made?

**Comment by pavelbedi** [comment] 2017-04-05 19:12
Wait for official Facebook Messenger app 😞

**Comment by karteek-paruchuri** [comment] 2017-04-05 19:14
@pavelbedi AFAIK they don't have any plans to release one anytime soon. But there's a messenger client that's internal to Facebook. It's slick and fast.

**Comment by cvx** [comment] 2017-04-05 19:17
@rsms I meant that we have to provide something like:

```javascript
window.debugModules = {};
window.__REACT_DEVOOLS_GLOBAL_HOOK__= {
  inject: function(obj) {
    Object.assign(window.debugModules, obj);
  }
};
```

…and inject that before any of Messenger JS is executed. Then we'll have a bag of goodies, including `window.debugModules.Mount`. 😃

I don't know yet how to ensure injection at that exact time, any ideas?

Btw. is `developerExtrasEnabled` still doing anything? I can't inspect elements/access console/do anything useful with it. 😛

**Comment by ghost** [comment] 2017-04-05 19:54
Love this app- sadly the white screen of death appeared with me this afternoon, any chance of fixing it?? or is there another third party app that is similar ? Thanks.

**Comment by anekdamian** [comment] 2017-04-05 19:56
I don't know if it's of any help, but there's an app that is called "[FreeChat for Facebook Messenger](https://itunes.apple.com/us/app/freechat-for-facebook-messenger/id1077753332?mt=12)" and it's working correctly right now.

I personally prefer FB Mac Messenger because it uses the official icon and because FreeChat has an annoying "ding" sound everytime you start typing.

So my point is that FreeChat might be of help to figure out the part where FB Mac Messenger is failing. :)

Just my 2 cents.
![bitmoji](https://render.bitstrips.com/v2/cpanel/10117530-200740646_1-s1-v1.png?transparent=1&width=246)

**Comment by ibruno** [comment] 2017-04-05 20:02
@anekdamian I'm using FreeChat now, but this ding sound + icon and drag window lag is too bad :(

Waiting for fix on FB Mac Messenger too!

**Comment by anekdamian** [comment] 2017-04-05 20:07
@ibruno: As @thenexus00 and @karteek-paruchuri mentioned, there's another app called "[Goofy](http://www.goofyapp.com/)" that does the job better than FreeChat. I just installed it and tested. So far so good! :)

![bitmoji](https://render.bitstrips.com/v2/cpanel/7216901-200740646_1-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by russelltrafford** [comment] 2017-04-05 20:15
**All,** don't take this the wrong way, but I think further discussions on alternative apps need to be taken offline, as we have a few suggestions and its not very motivating to the developer of this app when others might jump ship so soon.

Yes, I know it might only be temporary, still not great for morale. And for the hopefully short time that this app will be out of action, hopefully we can just make do with Mobile Facebook Messenger apps or facebook.com or www.messenger.com

Lets bring this back to issue discussion/solutions for the bug

**Comment by thepatres** [comment] 2017-04-05 20:17
Strongly agree with @russelltrafford 

I'm just waiting for fix to be released, no need to switch to another apps, or write about switching. I just like this one!

www.messenger.com is enough for now.

**Comment by anekdamian** [comment] 2017-04-05 20:24
@russelltrafford @patriksimonic  I understand your point of view. But the reality is that most of the users that come here ( and I can include myself in that group ) come frustrated looking for a quick solution, since this is a real-time, daily-basis app that all of us use. Not a service that you would be using once in a while, or once a day and you can just wait for things to be fixed.

So I ask: Why or rather "how" to take the conversation about alternative solutions out of the sight of people? Since this is probably the first thread that people who are experiencing this issue come to. 

We want quick fixes to continue using the service as a standalone app (crucial feature when working on a tons-of-tabs kind of context and need this to be apart from your browser).

Now, loyalty is a different element that any app development team risks when they have an issue like this. And if anything, read the comments. People are looking for "temporary apps" that will do the job, while this one gets fixed (again, me included).

Nonetheless, I believe that at the end people will stay with the app that performs better in all aspects.

**Comment by waveman777** [comment] 2017-04-05 20:33
Good point @anekdamian. As for the Goofy, it doesn't work for me either, it only worked the first time I logged in, and when I restarted it, it behaves similarly to our app > white screen.

**Comment by MissFerrety** [comment] 2017-04-05 22:05
This issue just showed up for me today. I also saw an issue pop up with another FB chat project on github. I wonder whether Facebook revoked all Messenger-related app permissions or something?

**Comment by christianwpro** [comment] 2017-04-05 23:18
Same issue here. Just started today. Loads with blank white screen.

**Comment by rsms** [comment] 2017-04-06 01:49
Okay, I believe that I've fixed it. The changes were many but in the end main.js (the JavaScript that this app adds to messenger.com to alter its appearance and behavior) was shaved down significantly in size and complexity, and as a result the app is now also faster (loads faster.)

However, before pushing out a new release to everyone, can you guys please test this (signed) build to make sure it fixes it for you? CC @romanbitca @johankman @pavelbedi @felixSpark @ibruno @TGNYC @CvX

[Messenger-0.1.13.1491443132-a99171247910d406.zip](https://github.com/rsms/fb-mac-messenger/files/901255/Messenger-0.1.13.1491443132-a99171247910d406.zip)

Please let me know ASAP if this works and I'll put it out to everyone. Thanks!

**Comment by raxod502** [comment] 2017-04-06 01:53
It works great for me!

**Comment by rohandhruva** [comment] 2017-04-06 01:53
@rsms the new build works for me. Thanks for the quick fix!

**Comment by felixSpark** [comment] 2017-04-06 01:56
It works, thanks!

**Comment by rsms** [comment] 2017-04-06 01:57
Awesome. I will fix the settings menu shortcut which is broken in that build and then push out an update. Thanks guys.

**Comment by ghost** [comment] 2017-04-06 01:59
New build work for me.
Thank you.

**Comment by rsms** [comment] 2017-04-06 02:02
Released with [0.1.13.2017-04-06T01:56:34Z](https://fbmacmessenger.rsms.me/#releases)

**Closed as completed by rsms** 2017-04-06 02:02 UTC

**Comment by eexit** [comment] 2017-04-06 09:55
Thank you so much @rsms for your reactiveness!

**Comment by vamidi** [comment] 2017-04-06 10:08
Thank you @rsms it worked for me!!!

**Comment by zenopopovici** [comment] 2017-04-06 13:08
Thank you @rsms, we really appreciate the effort!

**Comment by russelltrafford** [comment] 2017-04-06 15:23
Thank you @rsms, fantastic work and impressively quick turnaround 😃  😃

**Comment by nghtstr** [comment] 2017-04-06 15:50
Thank you @rsms!! It is working a lot better now, and you are right about the faster start up times!

**Comment by anekdamian** [comment] 2017-04-06 16:19
Awesome work @rsms. Thank you for the fast turnaround! :3

**Comment by russelltrafford** [comment] 2017-04-06 16:21
I tested the released version via the normal Update process, works perfectly 👍

**Comment by karteek-paruchuri** [comment] 2017-04-06 23:18
Thanks @rsms for fixing it.

**Comment by makproductions** [comment] 2018-12-27 02:12
So i still faced this issue today when i installed a Fresh copy on my mac for the first time.

How to reproduce:
- 2 factor authentication turned on.
- Already logged in on your default web browser (Chrome in my case) which the app opens to verify login.

The redirect from the app results in showing a blank white page and the web browser (chrome) just shows my feed ( with no verification message ) 
 
How i fixed it:
- Make sure you are logged out of facebook on the default browser. 
- Sign in on the app (this will open the web browser and ask you to login to verify).
- Login on the browser and save the app mac as a trusted browser. 
- GO back to the app Messenger Menu > Reload App From server > Login again
And FIXED.

Summary,
If you are already logged in on facebook for the default web browser the 2-step authentication does not kick in, resulting in you constantly logging in on the app but hitting the white blank page. 

Hope this helps :)

**Comment by benomatis** [comment] 2019-01-14 14:29
> So i still faced this issue today when i installed a Fresh copy on my mac for the first time.
> 
> How to reproduce:
> 
> * 2 factor authentication turned on.
> * Already logged in on your default web browser (Chrome in my case) which the app opens to verify login.
> 
> The redirect from the app results in showing a blank white page and the web browser (chrome) just shows my feed ( with no verification message )
> 
> How i fixed it:
> 
> * Make sure you are logged out of facebook on the default browser.
> * Sign in on the app (this will open the web browser and ask you to login to verify).
> * Login on the browser and save the app mac as a trusted browser.
> * GO back to the app Messenger Menu > Reload App From server > Login again
>   And FIXED.
> 
> Summary,
> If you are already logged in on facebook for the default web browser the 2-step authentication does not kick in, resulting in you constantly logging in on the app but hitting the white blank page.
> 
> Hope this helps :)

@makproductions I just hit refresh a couple of minutes ago, and I ended up with a blank screen. Going through your steps unfortunately didn't resolve the issue for me... :(
